//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdtexEntities : DbContext
    {
        public bdtexEntities()
            : base("name=bdtexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<paudit01> paudit01 { get; set; }
        public virtual DbSet<mtraba_view00> mtraba_view00 { get; set; }
        public virtual DbSet<mtraba00> mtraba00 { get; set; }
        public virtual DbSet<mclien00> mclien00 { get; set; }
        public virtual DbSet<padcor00> padcor00 { get; set; }
        public virtual DbSet<pcoxes00> pcoxes00 { get; set; }
        public virtual DbSet<pdgorp00> pdgorp00 { get; set; }
        public virtual DbSet<pdefec01> pdefec01 { get; set; }
        public virtual DbSet<paudob00> paudob00 { get; set; }
    }
}
