//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class mclien00
    {
        public string cclien { get; set; }
        public string drzsoc { get; set; }
        public string dappat { get; set; }
        public string dapmat { get; set; }
        public string dnombr { get; set; }
        public string cagent { get; set; }
        public string cdcide { get; set; }
        public string ndcide { get; set; }
        public string creguc { get; set; }
        public string cpaise { get; set; }
        public string cciuda { get; set; }
        public string cznpos { get; set; }
        public string ddirec { get; set; }
        public string ntfcli01 { get; set; }
        public string ntfcli02 { get; set; }
        public string numfax { get; set; }
        public string drefer01 { get; set; }
        public string drefer02 { get; set; }
        public string ctpcli { get; set; }
        public string cfmtpa { get; set; }
        public string dserie { get; set; }
        public string ddiren { get; set; }
        public Nullable<byte> ndiasa { get; set; }
        public string spoedi { get; set; }
        public string setiqu { get; set; }
        public string sclien { get; set; }
        public string ctpclo { get; set; }
        public string cusuar { get; set; }
        public string svigen { get; set; }
        public System.DateTime fvigen { get; set; }
        public Nullable<decimal> padici { get; set; }
        public Nullable<int> qadici { get; set; }
        public string strade { get; set; }
        public string crespo { get; set; }
        public string stesti { get; set; }
        public string cclmas { get; set; }
        public string scosse { get; set; }
        public string socuse { get; set; }
        public string socuse2 { get; set; }
        public Nullable<decimal> pmamin { get; set; }
        public string dabrev { get; set; }
        public string cagin1 { get; set; }
        public string cagin2 { get; set; }
        public string drzabr { get; set; }
        public string flgsau { get; set; }
        public string nivaql { get; set; }
        public string cejcta { get; set; }
    }
}
