//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtraba_view00
    {
        public string ctraba { get; set; }
        public string dtraba { get; set; }
        public string dcargo { get; set; }
        public string straba { get; set; }
        public string dsecci { get; set; }
        public string xsecci { get; set; }
        public string xlnprd { get; set; }
        public string nlbele { get; set; }
    }
}
