//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtraba00
    {
        public string ctraba { get; set; }
        public string dtraba { get; set; }
        public string ccargo { get; set; }
        public string dcargo { get; set; }
        public string straba { get; set; }
        public string dappat { get; set; }
        public string dapmat { get; set; }
        public string dnombr { get; set; }
        public string clinea { get; set; }
        public string csecci { get; set; }
        public string careas { get; set; }
        public string clocal { get; set; }
        public string cempre { get; set; }
        public string ccncos { get; set; }
        public string ctptra { get; set; }
        public string ctppag { get; set; }
        public string nlbele { get; set; }
        public Nullable<System.DateTime> fingre { get; set; }
        public string dsecci { get; set; }
        public string xsecci { get; set; }
        public Nullable<System.DateTime> finico { get; set; }
        public Nullable<System.DateTime> ffinco { get; set; }
        public Nullable<System.DateTime> fnacim { get; set; }
        public Nullable<System.DateTime> fceses { get; set; }
        public string clnprd { get; set; }
        public string clnprd01 { get; set; }
    }
}
