//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class padcor00
    {
        public string ctpord { get; set; }
        public string nordpr { get; set; }
        public string nordct { get; set; }
        public string ccarub { get; set; }
        public Nullable<decimal> qpropo01 { get; set; }
        public Nullable<decimal> qpropo02 { get; set; }
        public Nullable<decimal> qpropo03 { get; set; }
        public Nullable<decimal> qpropo04 { get; set; }
        public Nullable<decimal> qpropo05 { get; set; }
        public Nullable<decimal> qpropo06 { get; set; }
        public Nullable<decimal> qpropo07 { get; set; }
        public Nullable<decimal> qpropo08 { get; set; }
        public Nullable<decimal> qpropo09 { get; set; }
        public Nullable<decimal> qpropo10 { get; set; }
        public Nullable<decimal> qpropo11 { get; set; }
        public Nullable<decimal> qpropo12 { get; set; }
        public Nullable<float> qlatiz { get; set; }
        public Nullable<float> qantiz { get; set; }
        public Nullable<float> qretiz { get; set; }
        public string cencog { get; set; }
        public string nmesas { get; set; }
        public string sservi { get; set; }
        public Nullable<System.DateTime> fprogr { get; set; }
        public Nullable<System.DateTime> frepro { get; set; }
        public Nullable<System.DateTime> fprmod { get; set; }
        public Nullable<System.DateTime> fprmof { get; set; }
        public string clnprd { get; set; }
        public string dobsav { get; set; }
        public string dobspl { get; set; }
        public string dobshb { get; set; }
        public string savios { get; set; }
        public Nullable<int> qgirad { get; set; }
        public Nullable<int> qcorte { get; set; }
        public Nullable<int> qhabil { get; set; }
        public Nullable<int> qdesco { get; set; }
        public Nullable<int> qdesmu { get; set; }
        public Nullable<System.DateTime> fmddes { get; set; }
        public Nullable<System.DateTime> fmddeh { get; set; }
        public string clnpre { get; set; }
        public Nullable<int> nperim { get; set; }
        public string nmodul { get; set; }
        public string stizad { get; set; }
        public string nordco { get; set; }
        public Nullable<decimal> qmixte { get; set; }
        public Nullable<decimal> qmixco { get; set; }
        public Nullable<decimal> qmixcl { get; set; }
        public Nullable<decimal> qmixha { get; set; }
        public string savcor { get; set; }
        public string scalid { get; set; }
        public Nullable<System.DateTime> fcalid { get; set; }
        public Nullable<int> qdepur { get; set; }
        public string sfinal { get; set; }
        public string sanula { get; set; }
        public string ndcref { get; set; }
        public Nullable<System.DateTime> fguref { get; set; }
        public string ctporc { get; set; }
        public string ndocum { get; set; }
        public Nullable<int> qingug { get; set; }
        public string dobref { get; set; }
        public string cprser { get; set; }
        public string sulcor { get; set; }
        public string savcom { get; set; }
        public string ntizad { get; set; }
        public string scorad { get; set; }
        public Nullable<System.DateTime> fchpco { get; set; }
        public string flgsby { get; set; }
    }
}
