//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class paudit01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paudit01()
        {
            this.pdefec01 = new HashSet<pdefec01>();
        }
    
        public string careas { get; set; }
        public System.DateTime faudit { get; set; }
        public short nsecue { get; set; }
        public string clinea { get; set; }
        public string ctpord { get; set; }
        public string nordpr { get; set; }
        public string nordct { get; set; }
        public string cmarbe { get; set; }
        public string ccarub { get; set; }
        public Nullable<short> npieza { get; set; }
        public string cencog { get; set; }
        public string citems { get; set; }
        public string ccolor { get; set; }
        public Nullable<int> npanos { get; set; }
        public string dtalla { get; set; }
        public Nullable<int> qtotal { get; set; }
        public string dlotes { get; set; }
        public string ctraba { get; set; }
        public string copera { get; set; }
        public string cprove { get; set; }
        public string cmaqui { get; set; }
        public string cturno { get; set; }
        public string cparti { get; set; }
        public string nordco { get; set; }
        public Nullable<byte> npacki { get; set; }
        public int nlotes { get; set; }
        public int nmuest { get; set; }
        public Nullable<int> pcierr { get; set; }
        public Nullable<short> nrecup { get; set; }
        public Nullable<short> nsegun { get; set; }
        public Nullable<decimal> porcen { get; set; }
        public string flgcie { get; set; }
        public short ndefec { get; set; }
        public string status { get; set; }
        public string dobser { get; set; }
        public string flgrau { get; set; }
        public Nullable<byte> nreaud { get; set; }
        public string caudit { get; set; }
        public string flgext { get; set; }
        public string cliref { get; set; }
        public Nullable<System.DateTime> fauref { get; set; }
        public Nullable<short> nseref { get; set; }
        public string cusuar { get; set; }
        public Nullable<System.DateTime> fcreac { get; set; }
        public Nullable<System.DateTime> fmodif { get; set; }
        public Nullable<byte> nordpo { get; set; }
        public Nullable<System.DateTime> fprogr { get; set; }
        public string caudpr { get; set; }
        public string drefpr { get; set; }
        public string ctpaud { get; set; }
        public string csuppl { get; set; }
        public string flgenv { get; set; }
        public string sanula { get; set; }
        public Nullable<byte> ndesap { get; set; }
        public string sautab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pdefec01> pdefec01 { get; set; }
    }
}
