//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class paudob00
    {
        public int idobse { get; set; }
        public Nullable<System.DateTime> fregis { get; set; }
        public string clinea { get; set; }
        public string dobser { get; set; }
        public string cusuar { get; set; }
    }
}
