//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcoxes00
    {
        public string ctpord { get; set; }
        public string nordpr { get; set; }
        public string cestil { get; set; }
        public string ccarub { get; set; }
        public string dcarub { get; set; }
        public Nullable<byte> ngrupo { get; set; }
        public string ccolor { get; set; }
        public string ccodcl { get; set; }
        public string cescli { get; set; }
        public Nullable<System.DateTime> fiscoh { get; set; }
        public Nullable<System.DateTime> ffscoh { get; set; }
        public Nullable<System.DateTime> fiscos { get; set; }
        public Nullable<System.DateTime> ffscos { get; set; }
        public Nullable<System.DateTime> fisco1 { get; set; }
        public Nullable<System.DateTime> ffsco1 { get; set; }
        public Nullable<System.DateTime> fidcos { get; set; }
        public Nullable<System.DateTime> ffdcos { get; set; }
        public Nullable<System.DateTime> fihabi { get; set; }
        public Nullable<System.DateTime> ffhabi { get; set; }
        public Nullable<System.DateTime> fiepco { get; set; }
        public Nullable<System.DateTime> ffepco { get; set; }
        public Nullable<System.DateTime> ficort { get; set; }
        public Nullable<System.DateTime> ffcort { get; set; }
        public Nullable<System.DateTime> firevt { get; set; }
        public Nullable<System.DateTime> ffrevt { get; set; }
        public Nullable<System.DateTime> fiingt { get; set; }
        public Nullable<System.DateTime> ffingt { get; set; }
        public Nullable<System.DateTime> facr { get; set; }
        public Nullable<System.DateTime> fiacat { get; set; }
        public Nullable<System.DateTime> ffacat { get; set; }
        public Nullable<System.DateTime> fitent { get; set; }
        public Nullable<System.DateTime> fftent { get; set; }
        public Nullable<System.DateTime> fitert { get; set; }
        public Nullable<System.DateTime> fftert { get; set; }
        public Nullable<System.DateTime> fidefr { get; set; }
        public Nullable<System.DateTime> ffdefr { get; set; }
        public Nullable<System.DateTime> fiintj { get; set; }
        public Nullable<System.DateTime> ffintj { get; set; }
        public Nullable<System.DateTime> fidesh { get; set; }
        public Nullable<System.DateTime> ffdesh { get; set; }
        public Nullable<System.DateTime> fiingh { get; set; }
        public Nullable<System.DateTime> ffingh { get; set; }
        public Nullable<System.DateTime> falabd { get; set; }
        public Nullable<System.DateTime> faprot { get; set; }
        public string dlnprd { get; set; }
        public Nullable<System.DateTime> fiacab { get; set; }
        public Nullable<System.DateTime> ffacab { get; set; }
        public Nullable<System.DateTime> fiprad { get; set; }
        public Nullable<System.DateTime> ffprad { get; set; }
        public Nullable<System.DateTime> ficohi { get; set; }
        public Nullable<System.DateTime> ffcohi { get; set; }
        public Nullable<System.DateTime> fideco { get; set; }
        public Nullable<System.DateTime> ffdeco { get; set; }
        public Nullable<System.DateTime> fiemop { get; set; }
        public Nullable<System.DateTime> ffemop { get; set; }
        public Nullable<byte> ndespa { get; set; }
        public Nullable<byte> nordcs { get; set; }
        public string dtpemb { get; set; }
        public string ddesti { get; set; }
        public Nullable<int> qitere { get; set; }
        public Nullable<int> qitems { get; set; }
        public Nullable<int> qgirad { get; set; }
        public Nullable<int> qcorte { get; set; }
        public Nullable<int> qhabil { get; set; }
        public Nullable<int> qdespf { get; set; }
        public Nullable<int> qdesse { get; set; }
        public Nullable<int> qcospf { get; set; }
        public Nullable<int> qcosse { get; set; }
        public Nullable<int> qsm1pf { get; set; }
        public Nullable<int> qsm1se { get; set; }
        public Nullable<int> qingac { get; set; }
        public Nullable<int> qencaj { get; set; }
        public string citems { get; set; }
        public string chespe { get; set; }
        public string dhespe { get; set; }
        public string cestij { get; set; }
        public string dcaruj { get; set; }
        public string cservi { get; set; }
        public Nullable<System.DateTime> filavt { get; set; }
        public Nullable<System.DateTime> fflavt { get; set; }
        public Nullable<System.DateTime> ffrcos { get; set; }
        public Nullable<System.DateTime> fiepra { get; set; }
        public Nullable<System.DateTime> ffepra { get; set; }
        public Nullable<System.DateTime> fingru { get; set; }
        public Nullable<System.DateTime> fingtd { get; set; }
        public Nullable<System.DateTime> fiehit { get; set; }
        public Nullable<System.DateTime> ffehit { get; set; }
        public Nullable<System.DateTime> faprmu { get; set; }
        public Nullable<System.DateTime> firprc { get; set; }
        public Nullable<System.DateTime> ffrprc { get; set; }
        public Nullable<System.DateTime> ffraca { get; set; }
        public Nullable<int> qleadt { get; set; }
        public string cprepa { get; set; }
        public string sprdsm { get; set; }
        public Nullable<System.DateTime> fifabw { get; set; }
        public Nullable<System.DateTime> fffabw { get; set; }
        public Nullable<System.DateTime> fitenh { get; set; }
        public Nullable<System.DateTime> fftenh { get; set; }
    }
}
