//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdefec01
    {
        public string careas { get; set; }
        public System.DateTime faudit { get; set; }
        public short nsecue { get; set; }
        public string clinea { get; set; }
        public string codigo { get; set; }
        public string coddef { get; set; }
        public short qcanti { get; set; }
        public string dobser { get; set; }
        public string cgrupo { get; set; }
        public string cardef { get; set; }
        public string imgdef { get; set; }
    
        public virtual paudit01 paudit01 { get; set; }
    }
}
