//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdgorp00
    {
        public string ctpord { get; set; }
        public string nordpr { get; set; }
        public System.DateTime femisi { get; set; }
        public string cclien { get; set; }
        public string cagent { get; set; }
        public string cestil { get; set; }
        public Nullable<byte> nversi { get; set; }
        public System.DateTime fembar { get; set; }
        public Nullable<System.DateTime> fembor { get; set; }
        public Nullable<System.DateTime> finipr { get; set; }
        public string nordco { get; set; }
        public string dobser { get; set; }
        public decimal iprepr { get; set; }
        public decimal ipresc { get; set; }
        public Nullable<decimal> imgcon { get; set; }
        public string smgcon { get; set; }
        public Nullable<decimal> imgcbr { get; set; }
        public Nullable<decimal> imguni { get; set; }
        public string smgcbr { get; set; }
        public string smguni { get; set; }
        public Nullable<decimal> ifctpr { get; set; }
        public string cpater { get; set; }
        public string cescli { get; set; }
        public string descli { get; set; }
        public string sprxco { get; set; }
        public string ctempo { get; set; }
        public string cdivis { get; set; }
        public Nullable<decimal> padici { get; set; }
        public Nullable<int> qtotal { get; set; }
        public string cdivge { get; set; }
        public string ctipre { get; set; }
        public string sexpor { get; set; }
        public Nullable<System.DateTime> ffrcos { get; set; }
        public Nullable<System.DateTime> ffraca { get; set; }
        public string slqxop { get; set; }
        public string sordpr { get; set; }
        public string cusuar { get; set; }
        public System.DateTime fulmod { get; set; }
        public string dobsct { get; set; }
        public Nullable<decimal> iprsda { get; set; }
        public string dobcrt { get; set; }
        public string speddm { get; set; }
        public string dobsfl { get; set; }
        public Nullable<decimal> ifleop { get; set; }
        public Nullable<decimal> pmerma { get; set; }
        public string cgrtal { get; set; }
        public string scpsia { get; set; }
        public string squali { get; set; }
        public string srevis { get; set; }
        public decimal pplane { get; set; }
        public Nullable<System.DateTime> fdispo { get; set; }
        public Nullable<System.DateTime> fconsu { get; set; }
        public string srutmp { get; set; }
        public Nullable<System.DateTime> fliqui { get; set; }
        public string splane { get; set; }
        public string dobsso { get; set; }
        public string ssaldo { get; set; }
        public Nullable<System.DateTime> fumliq { get; set; }
        public string scotiz { get; set; }
        public Nullable<decimal> iprhil { get; set; }
        public Nullable<int> nhojas { get; set; }
        public Nullable<System.DateTime> ffrbor { get; set; }
        public string slista { get; set; }
        public string slogis { get; set; }
        public string dconte { get; set; }
        public string smodpr { get; set; }
        public string stidis { get; set; }
        public Nullable<System.DateTime> flqaca { get; set; }
    }
}
